export enum KycDocumentType {
  ID_FRONT = 'ID_FRONT',
  ID_BACK = 'ID_BACK',
  SELFIE = 'SELFIE',
  PROPERTY_OWNERSHIP = 'PROPERTY_OWNERSHIP',
  LEASE_AGREEMENT = 'LEASE_AGREEMENT',
  UTILITY_BILL = 'UTILITY_BILL'
}